Dashboard - Ruby On Rails/excel/config/routes.rb
Rails.application.routes.draw do
 
  get 'userrolemaps/show'

  #resources :users

  
  #root to: 'users#new'
  
  resources :sessions
  root to:'sessions#login'

  get 'sessions/login'

  get 'sessions/home'

  get 'sessions/profile'

  get 'sessions/setting'

  get 'users/new'

  resources :products

  root to: 'products#index'

  resources :userrolemaps

  root to: 'userrolemaps#index'

	
	match ':controller/:action/(:id)', via: [:get, :post]
  
  
  get "/path/to/your/tdk/page", to: "userrolemaps#tdk", as: "tdk"
   get "/path/to/your/tdk_operators/page", to: "userrolemaps#tdk_operators", as: "tdk_operators"

   get "/path/to/your/funding_operators/page", to: "userrolemaps#funding_operators", as: "funding_operators"

   get "/path/to/your/qc_operators/page", to: "userrolemaps#qc_operators", as: "qc_operators"
     get "/path/to/your/qcd_operators/page", to: "userrolemaps#qcd_operators", as: "qcd_operators"

   get "/path/to/your/authors_operators/page", to: "userrolemaps#authors_operators", as: "authors_operators"

  get "/path/to/your/addresses_operators/page", to: "userrolemaps#addresses_operators", as: "addresses_operators"
   

  get "/path/to/your/qc/page", to: "userrolemaps#qc", as: "qc"
    get "/path/to/your/qcd/page", to: "userrolemaps#qcd", as: "qcd"

  get "/path/to/your/funding/page", to: "userrolemaps#funding", as: "funding"

  get "/path/to/your/dispatched/page", to: "userrolemaps#dispatched", as: "dispatched"
get "/path/to/your/dispatchedd/page", to: "userrolemaps#dispatchedd", as: "dispatchedd"
  
   # post "/path/to/your/dispatched/page", to: "userrolemaps#dispatched", as: "dispatched"

	get "/path/to/your/welcome/page", to: "userrolemaps#welcome", as: "welcome"
	get "/path/to/your/index1/page", to: "userrolemaps#index1", as: "index1"

	get "/path/to/your/authors/page", to: "userrolemaps#authors", as: "authors"

	get "/path/to/your/addresses/page", to: "userrolemaps#addresses", as: "addresses"
  root :to => "sessions#login"
match "signup", :to => "users#new", via: [:get, :post]
match "login", :to => "sessions#login",via: [:get, :post]
match "logout", :to => "sessions#logout",via: [:get, :post]
match "home", :to => "sessions#home",via: [:get, :post]
match "profile", :to => "sessions#profile",via: [:get, :post]
match "setting", :to => "sessions#setting",via: [:get, :post]
match "dispatched", :to=> "userrolemaps#dispatched", via: [:get, :post]
end

Dashboard - Ruby On Rails/excel/app/models/userrolemap.rb
require 'csv'
class Userrolemap < ApplicationRecord
def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |detail|
      csv << detail.attributes
    end
  end
end
end

Dashboard - Ruby On Rails/excel/app/controllers/userrolemaps_controller.rb
class UserrolemapsController < ApplicationController
	before_action :authenticate_user, :only => [:index, :profile, :setting, :index1]
#before_action :save_login_state, :only => [:login, :login_attempt]
 
	def index
		@role1 = Role.select("roleID").where(roleName: 'TKA').map(&:roleID).uniq
		@operators1 = User.where("mapRoleID = ?", @role1 ).count
		@status1 = Role.select("queueStatusID").where(roleName: 'TKA').map(&:queueStatusID).uniq
		@files1 = Itemqueuedetail.where("queueStatusID =?",@status1).count
		@progress1 = Itemqueuedetail.where("queueStatusID =? AND status = '1' ",@status1).count

		@role2 = Role.select("roleID").where(roleName: 'Funding').map(&:roleID).uniq
		@operators2 = User.where("mapRoleID =?" , @role2).count
		@status2 = Role.select("queueStatusID").where(roleName: 'Funding').map(&:queueStatusID).uniq
		@files2 = Itemqueuedetail.where("queueStatusID =?",@status2).count
		@progress2 = Itemqueuedetail.where("queueStatusID = ? AND status ='1'", @status2).count

		@role3 = Role.select("roleID").where(roleName: 'QCA').map(&:roleID).uniq
		@operators3 = User.where("mapRoleID = ?", @role3).count
		@status3 = Role.select("queueStatusID").where(roleName: 'QCA').map(&:queueStatusID).uniq
		@files3 = Itemqueuedetail.where("queueStatusID =?",@status3).count
		@progress3 = Itemqueuedetail.where("queueStatusID =? AND status ='1'",@status3).count

		@status4 = Role.select("queueStatusID").where(roleName: 'Completed').map(&:queueStatusID).uniq
		@files4 = Itemqueuedetail.where("queueStatusID =?",@status4).count
		#@excel = Itemdetail.joins('INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID WHERE itemqueuedetails.queueStatusID = 1 AND itemqueuedetails.status = "0"')
		respond_to do |format|
  			format.html
  			format.csv { send_data @excel.to_csv }
  			format.xls 
		end

		#@excel1 = Itemdetail.joins('INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID WHERE itemqueuedetails.queueStatusID = 2 AND itemqueuedetails.status = "0"')
		respond_to do |format|
  			format.html
  			format.csv { send_data @excel1.to_csv }
  			format.xls 
		end
		
		respond_to do |format|
  			format.html
  			format.csv { send_data @excel2.to_csv }
  			format.xls 
		end

		respond_to do |format|
  			format.html
  			format.csv { send_data @excel3.to_csv }
  			format.xls 
		end
	end

	def tdk
		if params[:accession] != ''
		@accession =	params[:accession]
		else
		@accession	= ".*"
		end
		if params[:journal] != ''
		@journal =	params[:journal]
		else
		@journal = ".*"
		end
		@status1 = Role.select("queueStatusID").where(roleName: 'TKA').map(&:queueStatusID).uniq
		@details = if params[:datetimepicker1]
			Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status1[0].to_s).where("itemqueuedetails.status = '1' AND (journalSequence REGEXP ? AND accessionItemNo REGEXP ? AND itemdetails.created_at BETWEEN ? AND ?) ","#{@journal}","#{@accession}" ,"#{params[:datetimepicker1]}","#{params[:datetimepicker2]}")
			else
				Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status1[0].to_s).where("itemqueuedetails.status = '1'")
			end
		@excel = if params[:datetimepicker1]
			Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status1[0].to_s).where("itemqueuedetails.status = '1' AND (journalSequence REGEXP ? AND accessionItemNo REGEXP ? AND itemdetails.created_at BETWEEN ? AND ?) ","#{@journal}","#{@accession}" ,"#{params[:datetimepicker1]}","#{params[:datetimepicker2]}")
			else
				Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status1[0].to_s).where("itemqueuedetails.status = '1'")
			end
		#respond_to do |format|
  		#	format.html
  		#	format.csv { send_data @excel.to_csv }
  		#	format.xls 
		#end
		
	end

	def funding
		if params[:accession] != ''
		@accession =	params[:accession]
		else
		@accession	= ".*"
		end
		if params[:journal] != ''
		@journal =	params[:journal]
		else
		@journal = ".*"
		end
		@status2 = Role.select("queueStatusID").where(roleName: 'Funding').map(&:queueStatusID).uniq
		@details = if params[:datetimepicker1]
			Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status2[0].to_s).where("itemqueuedetails.status = '1' AND (journalSequence REGEXP ? AND accessionItemNo REGEXP ? AND itemdetails.created_at BETWEEN ? AND ?) ","#{@journal}","#{@accession}" ,"#{params[:datetimepicker1]}","#{params[:datetimepicker2]}")
			else
				Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status2[0].to_s).where("itemqueuedetails.status = '1'")
			end
		@excel1 = if params[:datetimepicker1]
			Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status2[0].to_s).where("itemqueuedetails.status = '1' AND (journalSequence REGEXP ? AND accessionItemNo REGEXP ? AND itemdetails.created_at BETWEEN ? AND ?) ","#{@journal}","#{@accession}" ,"#{params[:datetimepicker1]}","#{params[:datetimepicker2]}")
			else
				Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status2[0].to_s).where("itemqueuedetails.status = '1'")
			end
		
	end

	def qc
		if params[:accession] != ''
		@accession =	params[:accession]
		else
		@accession	= ".*"
		end
		if params[:journal] != ''
		@journal =	params[:journal]
		else
		@journal = ".*"
		end
		@status3 = Role.select("queueStatusID").where(roleName: 'QCA').map(&:queueStatusID).uniq
		@details = if params[:datetimepicker1]
			Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status3[0].to_s).where("itemqueuedetails.status = '1' AND (journalSequence REGEXP ? AND accessionItemNo REGEXP ? AND itemdetails.created_at BETWEEN ? AND ?) ","#{@journal}","#{@accession}" ,"#{params[:datetimepicker1]}","#{params[:datetimepicker2]}")
			else
				Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status3[0].to_s).where("itemqueuedetails.status = '1'")
			end
		@excel2 = if params[:datetimepicker1]
			Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status3[0].to_s).where("itemqueuedetails.status = '1' AND (journalSequence REGEXP ? AND accessionItemNo REGEXP ? AND itemdetails.created_at BETWEEN ? AND ?) ","#{@journal}","#{@accession}" ,"#{params[:datetimepicker1]}","#{params[:datetimepicker2]}")
			else
				Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status3[0].to_s).where("itemqueuedetails.status = '1'")
			end
		
	end

	def dispatched
		if params[:accession] != ''
		@accession =	params[:accession]
		else
		@accession	= ".*"
		end
		if params[:journal] != ''
		@journal =	params[:journal]
		else
		@journal = ".*"
		end
		@status4 = Role.select("queueStatusID").where(roleName: 'Completed').map(&:queueStatusID).uniq
		@details = if params[:datetimepicker1]
			Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status4[0].to_s).where("itemqueuedetails.status = '0' AND (journalSequence REGEXP ? AND accessionItemNo REGEXP ? AND itemdetails.created_at BETWEEN ? AND ?) ","#{@journal}","#{@accession}" ,"#{params[:datetimepicker1]}","#{params[:datetimepicker2]}")
			else
				Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status4[0].to_s).where("itemqueuedetails.status = '0'")
			end
		@excel3 = if params[:datetimepicker1]
			Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status4[0].to_s).where("itemqueuedetails.status = '0' AND (journalSequence REGEXP ? AND accessionItemNo REGEXP ? AND itemdetails.created_at BETWEEN ? AND ?) ","#{@journal}","#{@accession}" ,"#{params[:datetimepicker1]}","#{params[:datetimepicker2]}")
			else
				Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status4[0].to_s).where("itemqueuedetails.status = '0'")
			end
		
	end

	def authors
		if params[:accession] != ''
		@accession =	params[:accession]
		else
		@accession	= ".*"
		end
		if params[:journal] != ''
		@journal =	params[:journal]
		else
		@journal = ".*"
		end
		@status5 = Role.select("queueStatusID").where(roleName: 'Author').map(&:queueStatusID).uniq
		@details = if params[:datetimepicker1]
			Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status5[0].to_s).where("itemqueuedetails.status = '0' AND (journalSequence REGEXP ? AND accessionItemNo REGEXP ? AND itemdetails.created_at BETWEEN ? AND ?) ","#{@journal}","#{@accession}" ,"#{params[:datetimepicker1]}","#{params[:datetimepicker2]}")
			else
				Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status5[0].to_s).where("itemqueuedetails.status = '0'")
			end
		@excel4 = if params[:datetimepicker1]

Dashboard - Ruby On Rails/excel/app/helpers/userrolemaps_helper.rb
module UserrolemapsHelper
end

Dashboard - Ruby On Rails/excel/app/views/userrolemaps/addresses.html.erb
<%= button_to 'Main Page',index1_path,method: :get,class: "button2" %>
</br>
<p>ADDRESSES</p>
<%= form_tag(addresses_path, method: :get) do %>
<table class="table">
<tr class="tr">
<% @my_date1 = Time.now - 4.years %>
<% @my_date2 = Time.now %>
<td>AccessionItemNo:<%= text_field_tag :accession %></td>
<td>JournalSequence:<%= text_field_tag :journal %></td>
<td>SDate:<div class="container" style="width:100%;">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <!-- <input type='text' class="form-control" /> -->
                    <div class="input-group-addon" style="width:100%;">
                        <%= text_field_tag :datetimepicker1 %>
                        <span class="glyphicon glyphicon-calendar"></span>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
    $('#datetimepicker1').datetimepicker({
        format : 'YYYY-MM-DD HH:mm',
        defaultDate: "11/1/2013"
                    
    });
});
        </script>
    </div>
</div></td>
<td>EDate:<div class="container"  style="width:100%;">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker2'>
                    <!-- <input type='text' class="form-control" /> -->
                    <div class="input-group-addon"  style="width:100%;">
                        <%= text_field_tag :datetimepicker2 %>
                        <span class="glyphicon glyphicon-calendar"></span>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                var date=new Date().getFullYear();
                var month=parseInt(new Date().getMonth());
                month=month+1;
                date=date+"-"+month.toString();
                date=date+"-"+new Date().getDate();
                date=date+" "+new Date().getHours();
                date=date+":"+new Date().getMinutes();
                console.log(date.toString());
    $('#datetimepicker2').datetimepicker({
        format : 'YYYY-MM-DD HH:mm',
        defaultDate: date.toString()
                    
    });
    
});
        </script>
    </div>
</div></td>

<td><%= submit_tag 'Search' %></td>
</tr>
</table>
<% end %>
	<table class="table">
	<tr class="tr">
		<td>Date</td>
		<td>ItemID</td>
		<td>AccessionItemNo</td>
		<td>JournalSequence</td>
		<td>Priority</td>
		<td>Workflow</td>	
        <td>JobName</td>
	</tr>
<% for t in @details %>
	<tr class="tr">
	<td><%= t.created_at %></td>
	<td><%= t.itemID %></td>
	<td><%= t.accessionItemNo %></td>
	<td><%= t.journalSequence %></td>
	<td><%= t.priority %>
		<%= form_tag(:action => 'updateAddresses') do %>
		<%= text_field_tag(:priority) %>
		<%= hidden_field_tag 'id' , t.itemID %>
		<%= submit_tag "Change", :class =>"tabbutton" %>
  		<% end %></td>
	<td><%= link_to 'Show', {:action => 'show', :id => t.itemID},class: "show", :onclick=>"window.open(this.href,'show_details', 'height=600, width=600');return false;" %></td>
	<td><%= t.jobName %></td>
    </tr>
<% end %>
</table>
<p style="text-shadow: 0px 0px black;">
Download:
<%= link_to "Excel", addresses_path(request.parameters.merge({format: :xls})), 
    download: 'addresses.xls' %>
</p>

Dashboard - Ruby On Rails/excel/app/views/userrolemaps/addresses_operators.html.erb
<%= link_to 'Main Page',index1_path %>
<p>ADDRESSES OPERATORS</p>
	<table class="table">
	<tr class="tr">
		<td>ID</td>
		<td>MapRoleID</td>
		<td>UserName</td>	
	</tr>
<% for t in @details %>
	<tr class="tr">
	<td><%= t.id %></td>
	<td><%= t.mapRoleID %></td>
	<td><%= t.username %></td>
	</tr>
<% end %>
</table>

Dashboard - Ruby On Rails/excel/app/views/userrolemaps/authors.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ItemID</Data></Cell>
        <Cell><Data ss:Type="String">AccessionItemNo</Data></Cell>
        <Cell><Data ss:Type="String">JournalSequence</Data></Cell>
      </Row>
    <% @excel4.each do |operator| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= operator.itemID %></Data></Cell>
        <Cell><Data ss:Type="String"><%= operator.accessionItemNo %></Data></Cell>
        <Cell><Data ss:Type="String"><%= operator.journalSequence %></Data></Cell>
        
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

Dashboard - Ruby On Rails/excel/app/views/userrolemaps/dispatched.html.erb
<%= button_to 'Main Page',userrolemaps_path,method: :get,class: "button2" %>
</br>
<p>DISPATCHED</p>
<%= form_tag(dispatched_path, method: :get) do %>
<table class="table">
<tr class="tr">
<% @my_date1 = Time.now - 4.years %>
<% @my_date2 = Time.now %>
<td>Start Date<%= select_date( @my_date1 ,prompt: true,prefix: :start_date) %></td>
<td>Last Date<%= select_date( @my_date2 ,prompt: true,prefix: :end_date) %></td>
<td>AccessionItemNo:<%= text_field_tag :accession %></td>
<td>JournalSequence:<%= text_field_tag :journal %></td>
<td>SDate:<div class="container" style="width:100%;">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <!-- <input type='text' class="form-control" /> -->
                    <div class="input-group-addon" style="width:100%;">
                        <%= text_field_tag :datetimepicker1 %>
                        <span class="glyphicon glyphicon-calendar"></span>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
    $('#datetimepicker1').datetimepicker({
        format : 'YYYY-MM-DD HH:mm',
        defaultDate: "11/1/2013"
                    
    });
});
        </script>
    </div>
</div></td>
<td>EDate:<div class="container"  style="width:100%;">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker2'>
                    <!-- <input type='text' class="form-control" /> -->
                    <div class="input-group-addon"  style="width:100%;">
                        <%= text_field_tag :datetimepicker2 %>
                        <span class="glyphicon glyphicon-calendar"></span>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                var date=new Date().getFullYear();
                var month=parseInt(new Date().getMonth());
                month=month+1;
                date=date+"-"+month.toString();
                date=date+"-"+new Date().getDate();
                date=date+" "+new Date().getHours();
                date=date+":"+new Date().getMinutes();
                console.log(date.toString());
    $('#datetimepicker2').datetimepicker({
        format : 'YYYY-MM-DD HH:mm',
        defaultDate: date.toString()
                    
    });
    
});
        </script>
    </div>
</div></td>

<td><%= submit_tag 'Search' %></td>
</tr>
</table>
<% end %>

	<table class="table">
	<tr class="tr">
		<td>Date</td>
		<td>ItemID</td>
		<td>AccessionItemNo</td>
		<td>JournalSequence</td>
		<td>Priority</td>
		<td>Workflow</td>
        <td>JobName</td>	
	</tr>
<% for t in @details %>
	<tr class="tr">
	<td><%= t.created_at %></td>
	<td><%= t.itemID %></td>
	<td><%= t.accessionItemNo %></td>
	<td><%= t.journalSequence %></td>
	<td><%= t.priority %>
		<%= form_tag(:action => 'updateDispatched') do %>
		<%= text_field_tag(:priority) %>
		<%= hidden_field_tag 'id' , t.itemID %>
		<%= submit_tag("Change") %>
  		<% end %></td>
	<td><%= link_to 'Show', {:action => 'show', :id => t.itemID}, :onclick=>"window.open(this.href,'show_details', 'height=600, width=600');return false;" %></td>
    <td><%= t.jobName %></td>
	</tr>
<% end %>
</table>
<p style="text-shadow: 0px 0px black;">
Download:
<%= link_to "Excel", dispatched_path(request.parameters.merge({format: :xls})), 
    download: 'dispatched.xls' %>
</p>

Dashboard - Ruby On Rails/excel/app/views/userrolemaps/qc.html.erb
<%= button_to 'Main Page',userrolemaps_path,method: :get,class: "button2" %>
</br>
<p>QC</p>
<%= form_tag(qc_path, method: :get) do %>
<table class="table">
<tr class="tr">
<% @my_date1 = Time.now - 4.years %>
<% @my_date2 = Time.now %>
<td>Start Date<%= select_date( @my_date1 ,prompt: true,prefix: :start_date) %></td>
<td>Last Date<%= select_date( @my_date2 ,prompt: true,prefix: :end_date) %></td>
<td>AccessionItemNo:<%= text_field_tag :accession %></td>
<td>JournalSequence:<%= text_field_tag :journal %></td>
<td>SDate:<div class="container" style="width:100%;">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <!-- <input type='text' class="form-control" /> -->
                    <div class="input-group-addon" style="width:100%;">
                        <%= text_field_tag :datetimepicker1 %>
                        <span class="glyphicon glyphicon-calendar"></span>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
    $('#datetimepicker1').datetimepicker({
        format : 'YYYY-MM-DD HH:mm',
        defaultDate: "11/1/2013"
                    
    });
});
        </script>
    </div>
</div></td>
<td>EDate:<div class="container"  style="width:100%;">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker2'>
                    <!-- <input type='text' class="form-control" /> -->
                    <div class="input-group-addon"  style="width:100%;">
                        <%= text_field_tag :datetimepicker2 %>
                        <span class="glyphicon glyphicon-calendar"></span>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                var date=new Date().getFullYear();
                var month=parseInt(new Date().getMonth());
                month=month+1;
                date=date+"-"+month.toString();
                date=date+"-"+new Date().getDate();
                date=date+" "+new Date().getHours();
                date=date+":"+new Date().getMinutes();
                console.log(date.toString());
    $('#datetimepicker2').datetimepicker({
        format : 'YYYY-MM-DD HH:mm',
        defaultDate: date.toString()
                    
    });
    
});
        </script>
    </div>
</div></td>

<td><%= submit_tag 'Search' %></td>
</tr>
</table>
<% end %>
<p style="text-shadow: 0px 0px black;">
Download:
<%= link_to "Excel", qc_path(request.parameters.merge({format: :xls})), 
    download: 'qc.xls' %>
</p>
	<table class="table">
	<tr class="tr">
		<td>Date</td>
		<td>ItemID</td>
		<td>AccessionItemNo</td>
		<td>JournalSequence</td>
		<td>Priority</td>
		<td>Workflow</td>
        <td>JobName</td>
	</tr>
<% for t in @details %>
	<tr class="tr">
	<td><%= t.created_at %></td>
	<td><%= t.itemID %></td>
	<td><%= t.accessionItemNo %></td>
	<td><%= t.journalSequence %></td>
	<td><%= t.priority %>
		<%= form_tag(:action => 'updateQc') do %>
		<%= text_field_tag(:priority) %>
		<%= hidden_field_tag 'id' , t.itemID %>
		<%= submit_tag("Change") %>
  		<% end %></td>
	<td><%= link_to 'Show', {:action => 'show', :id => t.itemID}, :onclick=>"window.open(this.href,'show_details', 'height=600, width=600');return false;" %></td>
    <td><%= t.jobName %></td>
	
	</tr>
<% end %>
</table>

Dashboard - Ruby On Rails/excel/app/views/userrolemaps/qc_operators.html.erb
<%= link_to 'Main Page',userrolemaps_path %>
<p>QC OPERATORS</p>
	<table class="table">
	<tr class="tr">
		<td>ID</td>
		<td>MapRoleID</td>
		<td>UserName</td>	
	</tr>
<% for t in @details %>
	<tr class="tr">
	<td><%= t.id %></td>
	<td><%= t.mapRoleID %></td>
	<td><%= t.username %></td>
	</tr>
<% end %>
</table>

Dashboard - Ruby On Rails/excel/app/views/userrolemaps/tdk_operators.html.erb
<%= link_to 'Main Page',userrolemaps_path %>
<p>TDK OPERATORS</p>
	<table class="table">
	<tr class="tr">
		<td>ID</td>
		<td>MapRoleID</td>
		<td>UserName</td>	
	</tr>
<% for t in @details %>
	<a href=""><tr class="tr">
	<td><%= t.id %></td>
	<td><%= t.mapRoleID %></td>
	<td><%= t.username %></td>
	</tr>
<% end %>
</table>