Dashboard - Ruby On Rails/excel/config/routes.rb
Rails.application.routes.draw do
 
  get 'userrolemaps/show'

  #resources :users

  
  #root to: 'users#new'
  
  resources :sessions
  root to:'sessions#login'

  get 'sessions/login'

  get 'sessions/home'

  get 'sessions/profile'

  get 'sessions/setting'

  get 'users/new'

  resources :products

  root to: 'products#index'

  resources :userrolemaps

  root to: 'userrolemaps#index'

	
	match ':controller/:action/(:id)', via: [:get, :post]
  
  
  get "/path/to/your/tdk/page", to: "userrolemaps#tdk", as: "tdk"
   get "/path/to/your/tdk_operators/page", to: "userrolemaps#tdk_operators", as: "tdk_operators"

   get "/path/to/your/funding_operators/page", to: "userrolemaps#funding_operators", as: "funding_operators"

   get "/path/to/your/qc_operators/page", to: "userrolemaps#qc_operators", as: "qc_operators"
     get "/path/to/your/qcd_operators/page", to: "userrolemaps#qcd_operators", as: "qcd_operators"

   get "/path/to/your/authors_operators/page", to: "userrolemaps#authors_operators", as: "authors_operators"

  get "/path/to/your/addresses_operators/page", to: "userrolemaps#addresses_operators", as: "addresses_operators"
   

  get "/path/to/your/qc/page", to: "userrolemaps#qc", as: "qc"
    get "/path/to/your/qcd/page", to: "userrolemaps#qcd", as: "qcd"

  get "/path/to/your/funding/page", to: "userrolemaps#funding", as: "funding"

  get "/path/to/your/dispatched/page", to: "userrolemaps#dispatched", as: "dispatched"
get "/path/to/your/dispatchedd/page", to: "userrolemaps#dispatchedd", as: "dispatchedd"
  
   # post "/path/to/your/dispatched/page", to: "userrolemaps#dispatched", as: "dispatched"

	get "/path/to/your/welcome/page", to: "userrolemaps#welcome", as: "welcome"
	get "/path/to/your/index1/page", to: "userrolemaps#index1", as: "index1"

	get "/path/to/your/authors/page", to: "userrolemaps#authors", as: "authors"

	get "/path/to/your/addresses/page", to: "userrolemaps#addresses", as: "addresses"
  root :to => "sessions#login"
match "signup", :to => "users#new", via: [:get, :post]
match "login", :to => "sessions#login",via: [:get, :post]
match "logout", :to => "sessions#logout",via: [:get, :post]
match "home", :to => "sessions#home",via: [:get, :post]
match "profile", :to => "sessions#profile",via: [:get, :post]
match "setting", :to => "sessions#setting",via: [:get, :post]
match "dispatched", :to=> "userrolemaps#dispatched", via: [:get, :post]
end

Dashboard - Ruby On Rails/excel/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Excel</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <script type="text/javascript">
  function load()
  {
    setTimeout("window.open(self.location,'_self');",1800000);
    var current=new Date();
    document.getElementById("time1").innerHTML="Last Refresh At:"+current.toLocaleString();
    var next=new Date(current.getTime()+1800000);
    document.getElementById("time2").innerHTML="Next Refresh At:"+next.toLocaleString();
    
  }  
  </script>
  <body onload="load()">
  <ul>
  <li><%= button_to "Home", welcome_path,method: :get, class: "navbuttons" %></li>
  <li><%= button_to "Process A", userrolemaps_path,method: :get, class: "navbuttons" %></li>
  <li><%= button_to "Process D", index1_path,method: :get, class: "navbuttons" %></li>
  <li class="hoverclass" style="float:right; background-color: #D50000; "><%= link_to "Logout", logout_path %></li>
</ul>
  
  <ul style="background-color: rgba(128,128,128,0); box-shadow:  0 12px 16px 0 rgba(0,0,0,0), 0 17px 50px 0 rgba(0,0,0,0);">
  <li style="color:white; padding:10px 10px 0px 10px;" id="time1"></li>
  <li style="color:white; padding:10px 10px 0px 10px;" id="time2"></li>
  </ul>
  
<%= yield %>
</body onload="load()">
</html>

Dashboard - Ruby On Rails/excel/app/views/layouts/layout1.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Excel</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 
<%= yield %>
<body>
</html>